version: "3.9"

services:
  redis:
    image: redis:7
    container_name: weather_redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  weatherapi:
    build: ./WeatherAPI
    container_name: weather_api
    restart: always
    ports:
      - "5002:80"    # HTTP
      - "5003:443"   # HTTPS
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis__Configuration=redis:6379  
    depends_on:
      - redis

volumes:
  redis_data:
